### ISSUE TITLE
in yaml file,  in the end there must be one empty line, otherwise yaml will be parsed ERROR.

### ISSUE THREAD

**Issue by ada-wang** [ada-wang/yaml-printer#1]
```
Profiles:

    TwoOrgsOrdererGenesis:
        <<: *ChannelDefaults
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *OrdererOrg
        Consortiums:
            SampleConsortium:
                Organizations:
                    - *Org1
                    - *Org2
    TwoOrgsChannel:
        Consortium: SampleConsortium
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *Org1
                - *Org2

```
there must be a empty line in the end of file. if yaml file miss '\n', should append '\n'.
